# Generated by Django 6.0 on 2025-12-18 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('grade', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='FirstInfoAnyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=250)),
                ('description_1', models.TextField()),
                ('title_2', models.CharField(blank=True, max_length=250, null=True)),
                ('description_2', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='SuccessfullyDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_title', models.CharField(max_length=150)),
                ('title_1', models.CharField(max_length=250)),
                ('description_1', models.TextField()),
                ('image_1', models.ImageField(blank=True, upload_to='images/')),
                ('title_2', models.CharField(blank=True, max_length=250, null=True)),
                ('description_2', models.TextField(blank=True, null=True)),
                ('image_2', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='TellUsAboutYourProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('industry', models.CharField()),
                ('budget', models.CharField(choices=[('<$25.000', '$25.000'), ('$50.000', '$50.000'), ('$100.000', '$100.000'), ('$300.000', '$300.000')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UsedTechnologyAndOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='FrequentlyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('first_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.firstinfoanyservice')),
            ],
        ),
    ]
