# Generated by Django 6.0 on 2025-12-18 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedtechnologyandothers',
            name='first_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.firstinfoanyservice'),
            preserve_default=False,
        ),
    ]
