# Generated by Django 6.0 on 2025-12-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_usedtechnologyandothers_first_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellusaboutyourproject',
            name='budget',
            field=models.CharField(choices=[('$25.000', '$25.000'), ('$50.000', '$50.000'), ('$100.000', '$100.000'), ('$300.000', '$300.000')], max_length=150),
        ),
    ]
