# Generated by Django 6.0 on 2025-12-22 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_tellusaboutyourproject_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedtechnologyandothers',
            name='image',
        ),
        migrations.CreateModel(
            name='UsedTechnologyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('used_techno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.usedtechnologyandothers')),
            ],
        ),
    ]
