# Generated by Django 6.0 on 2025-12-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_usedtechnologyandothers_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedtechnologyandothers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='UsedTechnologyImage',
        ),
    ]
