# Generated by Django 6.0 on 2026-01-16 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinoneapp', '0001_initial'),
        ('services', '0003_clientsopinion_category_firstinfoanyservice_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonopenposition',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.category'),
        ),
        migrations.AddField(
            model_name='commonstep',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.category'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.category'),
        ),
    ]
