# Generated by Django 6.0 on 2025-12-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinoneapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helperstatistic',
            name='statistic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helperstatistic', to='allinoneapp.statistic'),
        ),
    ]
