# Generated by Django 6.0 on 2025-12-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinoneapp', '0002_alter_helperstatistic_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='name',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
