# Generated by Django 6.0 on 2025-12-25 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinoneapp', '0003_statistic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonOpenPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='HelperOpenPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('common_op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allinoneapp.commonopenposition')),
            ],
        ),
    ]
