# Generated by Django 6.0 on 2025-12-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_teammembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helperlocation',
            name='country',
            field=models.CharField(help_text='include country or region', max_length=150),
        ),
        migrations.AlterField(
            model_name='location',
            name='zone',
            field=models.CharField(help_text='include zone or country', max_length=150),
        ),
    ]
